version: "3"

services:
  gitlab:
    image: gitlab/gitlab-ce:9.5.2-ce.0
    hostname: gitlab.example.com
    ports:
      - 80:80
      - 443:443
      - "22:22"
    volumes:
      - ${PWD}/gitlab/config:/etc/gitlab
      - ${PWD}/gitlab/logs:/var/log/gitlab
      - ${PWD}/gitlab/data:/var/opt/gitlab
    