version: "3"

services:
  proxy:
    image: jwilder/nginx-proxy:${PROXY_IMG_VERSION}
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  node:
    build:
      context: ./node
      args:
        - NODE_IMG_VERSION=${NODE_IMG_VERSION}
    working_dir: /app
    command: ['node', 'index.js']
    ports:
      - ${NODE_PORT}
    environment:
      - VIRTUAL_HOST=${NODE_HOST}
      - NODE_PORT=${NODE_PORT}
    volumes:
      - ./node:/app

  python:
    build:
      context: ./python
    working_dir: /app
    volumes:
      - ./python:/app
    command: ['python', 'flask_app.py']
    environment:
     - VIRTUAL_HOST=${PYTHON_HOST}
    ports:
      - '5000'
