version: "3"

services:
  proxy:
    image: jwilder/nginx-proxy:${PROXY_IMG_VERSION}
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  python:
    build:
      context: ./python
    working_dir: /app
    volumes:
      - ./python:/app
    command: ['python', 'flask_app.py']
    environment:
     - VIRTUAL_HOST=flask.test
    ports:
      - '5000'